### PR TITLE
Add definition for Entities.md

### PR DESCRIPTION
**Pull request by sfolsom**
Instead of defining authorities, controlled vocabularies, etc. we decided to define entities more broadly.

### CODE REVIEW

**Comment by sfolsom** [comment]
Addresses https://github.com/LD4/entity_metadata_management/issues/15

**Comment by sfolsom** [comment]
@vitustang @eslao @NancyJean @greeve can you take a look at this definition of entities to make sure I've have covered our previous discussions?

**Comment by vitustang** [comment]
Looks good to me. One possible addition is to add, in parentheses, after "An entity is any resource" (a thing or a concept) to forestall the question of "what is a resource"

**Comment by greeve** [comment]
I agree with @vitustang. I noticed a grammatical issue that needs attention. There is an errant **the** in the second sentence of the definition. Or you could remove the phrasing "what are sometimes referred to" this way:

> Entities include, but are not limited to, _authorities_, _controlled vocabulary terms_, or _real world objects (RWOs)_ in library, archives, and museum domains.

**Comment by sfolsom** [comment]
@vitustang and @greeve I've updated the definition based on your feedback. Could one of you review and approve the change if there are no further changes needed?

**Review by greeve — APPROVED** [review]
These changes are approved.

**Pull request merged**
