### PR TITLE
Make use of Activity types consistent in 4.3

### PR DESCRIPTION
**Pull request by eslao**
@NancyJean Tweaked language and added formatting where needed

### CODE REVIEW

**Review by zimeon — APPROVED** [review]

**Review by NancyJean — COMMENTED** [review]
Line 729 doesn't entirely make sense to me: "In the second scenario, the replacement entity or entities do not exist prior to the deprecation. In this case, the replacement entity or entities are created and the status of the original entity is changed to deprecated."
If you're saying they don't exist 'prior to deprecation' aren't you saying that deprecation already occurred?  If so, then you can't create them and then change the original to deprecated because the original is already deprecated.  So, how is this supposed to work when the original is already deprecated?  Is the deprecated entity edited? E.g., "In this case, the replacement entity or entities are created and the deprecated entity is edited to include the replacement(s)."
Regardless, the last word 'deprecrated' is misspelled in the doc.

Lines 731-33: 1) I think these should be described as 3 scenarios and reflect the change above (if correct) and 2) the last sentence should be on a new line.  So, proposing the following the changes:
"The three Entity Change Activity scenarios for 'Deprecate' occur when:
* an entity is deprecated and not replaced;
* an entity is deprecated and the replacement entity or entities already exist; and 
* an entity is deprecated and there is a subsequent replacement entity activity (e.g., to create, update, or add). 
In the latter two scenarios, it is expected that the consumer will dereference the deprecated entity URI to obtain the replacement entity description(s)."

Didn't we agree that one entity might be replaced by multiple entities? If so, that last sentence might need some clarification.

**Comment by zimeon** [comment]
I don't think we can specify if or when an entity that is deprecated might be edited. Ideally it would be edited at the moment of deprecation to indicate that and information about replacements, but there may be other workflows.

I agree that an entity may be replaced with multiple entities.

**Comment by sfolsom** [comment]
Could we just go with "There are two common scenarios. In the first, the replacement entity or entities already exist and the `Deprecate` activity updates the deprecated entity only. In the second scenario, the replacement entity or entities are created and the status of the original entity is changed to deprecrated."?

**Review by NancyJean — COMMENTED** [review]
I like what Simeon wrote as well as the simplicity Steven suggests.  How about changing line 729 to  - 
"Ideally an entity would be edited at the moment of deprecation, simultaneously indicating both the Deprecate activity and providing information about its replacement(s); however, there may be other editing workflows in which deprecation of an entity and information about its replacement(s) are generated separately."

And then delete lines 731-33 from  "The two scenarios . . . ." 
Would that work?

**Review by sfolsom — APPROVED** [review]

**Pull request merged**
